# frozen_string_literal: true

module Custom::Whatsapp::EvolutionGo::ProviderConfigDefaults
  DEFAULTS = {
    'ignore_groups' => true,
    'reject_call' => false,
    'msg_call' => '',
    'always_online' => false,
    'read_messages' => false,
    'ignore_status' => true,
    'proxy_enabled' => false,
    'proxy_host' => '',
    'proxy_port' => '',
    'proxy_username' => '',
    'proxy_password' => '',
    'sign_msg' => false,
    'sign_delimiter' => "\n",
    'mark_read_on_reply' => false,
    'mark_read_on_open' => true,
    'send_random_delay' => false,
    'notify_send_errors_private' => true,
    'convert_markdown_outbound' => true,
    'convert_markdown_inbound' => true,
    'merge_brazil_contacts' => true,
    'send_templates_as_text' => true,
    'ignore_from_me_echo' => true,
    'import_on_connect' => false,
    'import_contacts' => false,
    'import_status' => 'idle',
    'import_cursor' => {},
    'import_stats' => {},
    'import_error' => nil,
    'mutation_stats' => {},
    'mark_inbound_deleted' => true,
    'mark_inbound_edited' => true,
    'sync_delete_to_whatsapp' => false,
    'sync_edit_to_whatsapp' => false,
    'import_messages' => false,
    # Message count for POST /chat/history-sync `count` (key name kept for saved configs).
    'days_limit_import_messages' => 100,
    'connection_status' => 'close',
    'webhook_token' => nil,
    'webhook_subscribe' => Custom::Whatsapp::EvolutionGo::ProviderConfig::WEBHOOK_EVENTS
  }.freeze
end
