# frozen_string_literal: true

module Custom::Whatsapp::Evolution::ProviderConfigDefaults
  DEFAULTS = {
    'groups_ignore' => true,
    'reject_call' => false,
    'msg_call' => '',
    'always_online' => false,
    'read_messages' => false,
    'read_status' => false,
    'sync_full_history' => false,
    'proxy_enabled' => false,
    'proxy_host' => '',
    'proxy_port' => '',
    'proxy_protocol' => 'http',
    'proxy_username' => '',
    'proxy_password' => '',
    'sign_msg' => false,
    'conversation_pending' => false,
    'merge_brazil_contacts' => true,
    'mark_read_on_reply' => false,
    'sync_delete_to_whatsapp' => false,
    'convert_markdown_outbound' => true,
    'convert_markdown_inbound' => true,
    'send_templates_as_text' => true,
    'send_random_delay' => true,
    'notify_send_errors_private' => true,
    'ignore_jids' => ['@g.us'],
    'ignore_status_broadcast' => true,
    'ignore_from_me_echo' => true,
    'ignore_survey_links' => true,
    'format_group_messages' => false,
    'import_on_connect' => true,
    'sync_lost_messages' => false,
    'import_contacts' => false,
    'import_messages' => false,
    'days_limit_import_messages' => 7,
    'connection_status' => 'connecting',
    'import_status' => 'idle',
    'import_cursor' => {},
    'import_stats' => {},
    'import_error' => nil,
    'webhook_token' => nil
  }.freeze
end
